### ISSUE TITLE
请教,kona-pkix>text>TestUtils中测试用例报错:PBEWithHmacSM3AndSM4 SecretKeyFactory not available

### ISSUE THREAD

**Issue by zhk56** [Tencent/TencentKonaSMSuite#186]
背景介绍,我的私钥是国密加密后pkcs8的私钥,使用普通java环境无法加载,看到源码中有类似私钥以及加载方式,所以希望可以参考并使用下.下面是详细过程:
1,在kona-pkix的源码中,执行测试程序:
@Test
    public void testGeneratePrivateKeyWithEncryptedKey() throws Exception {
        testGeneratePrivateKey(TestUtils.encryptedRSAPrivateKeyAsFile(
                "ca-rsarsa_enc.key", "password"));
        testGeneratePrivateKey(TestUtils.encryptedECPrivateKeyAsFile(
                "ca-p256ecdsa_enc.key", "password"));
        testGeneratePrivateKey(TestUtils.encryptedECPrivateKeyAsFile(
                "ca-p256sm2_enc.key", "password"));
        testGeneratePrivateKey(TestUtils.encryptedECPrivateKeyAsFile(
                "ca-sm2ecdsa_enc.key", "password"));
        testGeneratePrivateKey(TestUtils.encryptedECPrivateKeyAsFile(
                "ca-sm2sm2_enc.key", "password"));
        testGeneratePrivateKey(TestUtils.encryptedECPrivateKeyAsFile(
                "PBEWithHmacSM3AndSM4", "EC",
                "ca-sm2sm2_enc-sm4.key", "password"));
    }
除了最后一个,全部正常执行,但是最后一个方法执行失败,报错:PBEWithHmacSM3AndSM4 SecretKeyFactory not available
巧的是,我需要使用ca-sm2sm2_enc-sm4.key此种类型的加密私钥.此段代码执行异常:
 testGeneratePrivateKey(TestUtils.encryptedECPrivateKeyAsFile(
                "PBEWithHmacSM3AndSM4", "EC",
                "ca-sm2sm2_enc-sm4.key", "password")
报错信息:
java.security.NoSuchAlgorithmException: PBEWithHmacSM3AndSM4 SecretKeyFactory not available

	at java.base/javax.crypto.SecretKeyFactory.<init>(SecretKeyFactory.java:122)
	at java.base/javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:168)
	at com.tencent.kona.pkix.TestUtils.encryptedPrivateKey(TestUtils.java:246)
	at com.tencent.kona.pkix.TestUtils.encryptedECPrivateKeyAsFile(TestUtils.java:224)
	at com.tencent.kona.pkix.provider.KeyFactoryTest.testGeneratePrivateKeyWithEncryptedKey(KeyFactoryTest.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

2,于是我又试了另一种方案,新建项目,引入kona-crypto,ssl,pkix的1.0.4版本的依赖,将此测试方案复制过来执行,又出现报错:
Exception in thread "main" java.io.IOException: PBE parameter parsing error: expecting the object identifier for a HmacSHA key derivation function
	at java.base/com.sun.crypto.provider.PBES2Parameters.parseKDF(PBES2Parameters.java:341)
	at java.base/com.sun.crypto.provider.PBES2Parameters.engineInit(PBES2Parameters.java:279)
	at java.base/java.security.AlgorithmParameters.init(AlgorithmParameters.java:312)
	at java.base/sun.security.x509.AlgorithmId.decodeParams(AlgorithmId.java:137)
	at java.base/sun.security.x509.AlgorithmId.<init>(AlgorithmId.java:119)
	at java.base/sun.security.x509.AlgorithmId.parse(AlgorithmId.java:384)
	at java.base/javax.crypto.EncryptedPrivateKeyInfo.<init>(EncryptedPrivateKeyInfo.java:98)
	at org.perfect99.testChart.GmSSL_PKCS8.encryptedPrivateKey(GmSSL_PKCS8.java:63)
	at org.perfect99.testChart.GmSSL_PKCS8.encryptedECPrivateKeyAsFile(GmSSL_PKCS8.java:56)
	at org.perfect99.testChart.GmSSL_PKCS8.main(GmSSL_PKCS8.java:47)
我认为是因为环境的原因,但是具体不明白为什么在贵司源码的测试程序,我也无法执行,希望解惑,最好能指明,在测试程序中,我该如何去做.

**Comment by johnshajiang** [comment]
1.0.5版才实现的`PBEWithHmacSM3AndSM4`。

**Comment by johnshajiang** [comment]
> 报错信息:
java.security.NoSuchAlgorithmException: PBEWithHmacSM3AndSM4 SecretKeyFactory not available

请问，你是如何执行这些测试的？
是使用的最新源代码吗？

**Comment by zhk56** [comment]
不好意思,写错了,是1.0.5,
启动方式在idea中的test方法上直接启动的,
使用命令./gradlew clean :kona-pkix:test --tests com.tencent.kona.pkix.provider.KeyFactoryTest,
报错如下:
PS E:\TencentKonaSMSuite> ./gradlew clean :kona-pkix:test --tests com.tencent.kona.pkix.provider.KeyFactoryTest
Starting a Gradle Daemon (subsequent builds will be faster)
BabaSSL is unavailable: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
BabaSSL is unavailable: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。

> Task :kona-crypto:compileJava
注: E:\TencentKonaSMSuite\kona-crypto\src\main\java\com\tencent\kona\crypto\provider\SM2Signature.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。

> Task :kona-pkix:compileJava
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

> Task :kona-pkix:compileTestJava
注: E:\TencentKonaSMSuite\kona-pkix\src\test\java\com\tencent\kona\pkix\common\Utils.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

> Task :kona-pkix:test FAILED

KeyFactoryTest > testGeneratePrivateKeyWithEncryptedKey() FAILED
    java.security.NoSuchAlgorithmException: PBEWithHmacSM3AndSM4 SecretKeyFactory not available
        at javax.crypto.SecretKeyFactory.<init>(SecretKeyFactory.java:122)
        at javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:160)
        at com.tencent.kona.pkix.TestUtils.encryptedPrivateKey(TestUtils.java:246)
KeyFactoryTest > testGetKeySpecs() PASSED
Test summary: Passed: 3, Failed: 1, Skipped: 0

4 tests completed, 1 failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kona-pkix:test'.
> There were failing tests. See the report at: file:///E:/TencentKonaSMSuite/kona-pkix/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s

**Comment by johnshajiang** [comment]
我刚才在一台Windows机器上新克隆了这个项目，然后执行上面的测试，能够成功结束。
```
git clone https://github.com/Tencent/TencentKonaSMSuite.git
cd TencentKonaSMSuite
./gradlew clean :kona-pkix:test --tests com.tencent.kona.pkix.provider.KeyFactoryTest
```

**Comment by johnshajiang** [comment]
那么，你用的JDK版本是什么？

**Comment by zhk56** [comment]
我的jdk版本是1.8.0_361,并且我使用11.0.18也测试过,使用命令行和idea内均是报同一个错误,我很苦恼

**Comment by johnshajiang** [comment]
看起来你用的是Oracle JDK 8u361，它对应于OpenJDK 8u262。
刚才下载了一个OpenJDK 8u362，也没有问题。不过，我无法使用Oracle JDK 8进行测试。
```
% ./gradlew --version

------------------------------------------------------------
Gradle 8.0.1
------------------------------------------------------------

Build time:   2023-02-17 20:09:48 UTC
Revision:     68959bf76cef4d28c678f2e2085ee84e8647b77a

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_362 (Temurin 25.362-b09)
OS:           Mac OS X 12.6 x86_64

**Comment by zhk56** [comment]
我替换成了openjdk 362
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (Temurin)(build 25.362-b09, mixed mode)
还是报同样的错误,我自己排查下问题吧,感谢您的帮助,由衷感谢

**Comment by johnshajiang** [comment]
如果问题排查有进展，也请告之，谢谢！

**Comment by zhk56** [comment]
好的
