### ISSUE TITLE
linux环境报错java.lang.ClassNotFoundException: sun.misc.JavaSecuritySignatureAccess

### ISSUE THREAD

**Issue by poyun** [Tencent/TencentKonaSMSuite#569]
测试环境不支持版本：
jdk1.8.0_202

我本地:
jdk1.8.0_371 支持

jdk1.8.0_202环境没有这个类，请问有没有好的解决方案？

Caused by: java.lang.ClassNotFoundException: sun.misc.JavaSecuritySignatureAccess
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.tencent.kona.jdk.internal.misc.SharedSecretsUtil.<clinit>(SharedSecretsUtil.java:99)

**Comment by johnshajiang** [comment]
请试试在java命令中加上系统属性`-Dcom.tencent.misc.useSharedSecrets=false`，这样就不会使用相关的内部实现类。

**Comment by johnshajiang** [comment]
@poyun 
使用系统属性`com.tencent.misc.useSharedSecrets`能够解决问题吗？
如果没有主动设置这个属性的值，那么在JDK 8上，它的默认值是`true`。

**Comment by johnshajiang** [comment]
一般还是建议在java命令中设置这些系统属性，在程序中设置，可能时机就晚了。它们只会被初始化一次。

不过，一般还是推荐使用高版本的JDK。
而且使用`SharedSecret`在安全性与性能上会更好一些。

**Comment by johnshajiang** [comment]
如果你认为这个问题已经得到解决了，请关闭该issue。
若有其它的问题，欢迎开新的issue。
