### ISSUE TITLE
请问SSL中的demo是没有实现双向认证吗

### ISSUE THREAD

**Issue by nhhc-lxr** [Tencent/TencentKonaSMSuite#636]
1. TLCPWithJettyDemo中，服务端和客户端都调用了createContext()方法，加载了相同的truststore和keystore，服务端并没有设置setNeedClientAuth(true);服务端注释掉truststore相关代码和客户端注释掉keystore相关代码后依然可以正常连接，是否可以理解为ssl模块demo包下提供的都是单向认证？
2. createServer()方法中加上了
```
contextFactory.setNeedClientAuth(true);
```
出现如下问题，看起来能够获取到返回结果，但是无法识别curveSM2？
```
2024-01-15 18:23:09.546:WARN:oejus.SslContextFactory:qtp728739494-31: EXCEPTION 
java.security.cert.CertificateParsingException: java.io.IOException: Unknown named curve: 1.2.156.10197.1.301
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:169)
	at sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1849)
	at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:189)
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:102)
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
	at org.eclipse.jetty.util.ssl.SslContextFactory.getX509CertChain(SslContextFactory.java:2049)
	at org.eclipse.jetty.util.ssl.SslContextFactory.getX509CertChain(SslContextFactory.java:2008)
	at org.eclipse.jetty.server.SecureRequestCustomizer.getCertChain(SecureRequestCustomizer.java:294)
	at org.eclipse.jetty.server.SecureRequestCustomizer.access$400(SecureRequestCustomizer.java:53)
	at org.eclipse.jetty.server.SecureRequestCustomizer$SslAttributes.getSslSessionData(SecureRequestCustomizer.java:384)
	at org.eclipse.jetty.server.SecureRequestCustomizer$SslAttributes.<init>(SecureRequestCustomizer.java:336)
	at org.eclipse.jetty.server.SecureRequestCustomizer.customize(SecureRequestCustomizer.java:283)
	at org.eclipse.jetty.server.SecureRequestCustomizer.customize(SecureRequestCustomizer.java:210)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:483)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:750)
Caused by: 
java.io.IOException: Unknown named curve: 1.2.156.10197.1.301
	at sun.security.util.ECParameters.engineInit(ECParameters.java:141)
	at java.security.AlgorithmParameters.init(AlgorithmParameters.java:293)
	at sun.security.x509.AlgorithmId.decodeParams(AlgorithmId.java:151)
	at sun.security.x509.AlgorithmId.<init>(AlgorithmId.java:133)
	at sun.security.x509.AlgorithmId.parse(AlgorithmId.java:413)
	at sun.security.x509.X509Key.parse(X509Key.java:168)
	at sun.security.x509.CertificateX509Key.<init>(CertificateX509Key.java:75)
	at sun.security.x509.X509CertInfo.parse(X509CertInfo.java:667)
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:167)
	at sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1849)
	at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:189)
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:102)
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
	at org.eclipse.jetty.util.ssl.SslContextFactory.getX509CertChain(SslContextFactory.java:2049)
	at org.eclipse.jetty.util.ssl.SslContextFactory.getX509CertChain(SslContextFactory.java:2008)
	at org.eclipse.jetty.server.SecureRequestCustomizer.getCertChain(SecureRequestCustomizer.java:294)
	at org.eclipse.jetty.server.SecureRequestCustomizer.access$400(SecureRequestCustomizer.java:53)
	at org.eclipse.jetty.server.SecureRequestCustomizer$SslAttributes.getSslSessionData(SecureRequestCustomizer.java:384)
	at org.eclipse.jetty.server.SecureRequestCustomizer$SslAttributes.<init>(SecureRequestCustomizer.java:336)
	at org.eclipse.jetty.server.SecureRequestCustomizer.customize(SecureRequestCustomizer.java:283)
	at org.eclipse.jetty.server.SecureRequestCustomizer.customize(SecureRequestCustomizer.java:210)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:483)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:750)
Hello!
```

**Comment by johnshajiang** [comment]
我在`TLCPWithJettyDemo::createServer()`方法的[这一行]加上语句`sslContextFactory.setNeedClientAuth(true);`是可以通信成功的。

我可以看到如下的日志，
```
"CertificateRequest": {
  "certificate types": [ecdsa_sign, rsa_sign]
  "supported signature algorithms": []
  "certificate authorities": [CN=tlcp-intca]
}
```

```
com.tencent.kona.ssl|FINE|81|HttpClient@1d572e62-24|2024-01-15 22:27:32.584 CST|TLCPCertificate.java:327|Produced client Certificate handshake message (
"Certificates": [
  "certificate" : {
    "version"            : "v3",
    "serial number"      : "4d:98:a4:22:6f:c7:f9:74:8d:56:c6:1c:7e:7e:12:b6:52:81:79",
    "signature algorithm": "SM3withSM2",
    "issuer"             : "CN=tlcp-intca",
    "not before"         : "2022-04-04 07:58:03.000 CST",
    "not  after"         : "2032-04-01 07:58:03.000 CST",
    "subject"            : "CN=localhost",
    "subject public key" : "EC",
...
```

```
com.tencent.kona.ssl|FINE|11|qtp484841769-17|2024-01-15 22:27:32.620 CST|TLCPCertificate.java:391|Consuming client Certificate handshake message (
"Certificates": [
  "certificate" : {
    "version"            : "v3",
    "serial number"      : "4d:98:a4:22:6f:c7:f9:74:8d:56:c6:1c:7e:7e:12:b6:52:81:79",
    "signature algorithm": "SM3withSM2",
    "issuer"             : "CN=tlcp-intca",
    "not before"         : "2022-04-04 07:58:03.000 CST",
    "not  after"         : "2032-04-01 07:58:03.000 CST",
    "subject"            : "CN=localhost",
    "subject public key" : "EC",
...
```

[这一行]:
https://github.com/Tencent/TencentKonaSMSuite/blob/master/kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLCPWithJettyDemo.java#L276

**Comment by nhhc-lxr** [comment]
> 我在`TLCPWithJettyDemo::createServer()`方法的[这一行](https://github.com/Tencent/TencentKonaSMSuite/blob/master/kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLCPWithJettyDemo.java#L276)加上语句`sslContextFactory.setNeedClientAuth(true);`是可以通信成功的。
> 
> 我可以看到如下的日志，
> 
> ```
> "CertificateRequest": {
>   "certificate types": [ecdsa_sign, rsa_sign]
>   "supported signature algorithms": []
>   "certificate authorities": [CN=tlcp-intca]
> }
> ```
> 
> ```
> com.tencent.kona.ssl|FINE|81|HttpClient@1d572e62-24|2024-01-15 22:27:32.584 CST|TLCPCertificate.java:327|Produced client Certificate handshake message (
> "Certificates": [
>   "certificate" : {
>     "version"            : "v3",
>     "serial number"      : "4d:98:a4:22:6f:c7:f9:74:8d:56:c6:1c:7e:7e:12:b6:52:81:79",
>     "signature algorithm": "SM3withSM2",
>     "issuer"             : "CN=tlcp-intca",
>     "not before"         : "2022-04-04 07:58:03.000 CST",
>     "not  after"         : "2032-04-01 07:58:03.000 CST",
>     "subject"            : "CN=localhost",
>     "subject public key" : "EC",
> ...
> ```
> 
> ```
> com.tencent.kona.ssl|FINE|11|qtp484841769-17|2024-01-15 22:27:32.620 CST|TLCPCertificate.java:391|Consuming client Certificate handshake message (
> "Certificates": [
>   "certificate" : {
>     "version"            : "v3",
>     "serial number"      : "4d:98:a4:22:6f:c7:f9:74:8d:56:c6:1c:7e:7e:12:b6:52:81:79",
>     "signature algorithm": "SM3withSM2",
>     "issuer"             : "CN=tlcp-intca",
>     "not before"         : "2022-04-04 07:58:03.000 CST",
>     "not  after"         : "2032-04-01 07:58:03.000 CST",
>     "subject"            : "CN=localhost",
>     "subject public key" : "EC",
> ...
> ```

首先感谢大佬回复，我仔细看了debug日志，确实连接成功了，但是会出现证书转化失败的问题
我删掉了主楼中多余的报错信息，麻烦您帮忙看一下

其次就是在kona-demo模块的[这一行](https://github.com/Tencent/TencentKonaSMSuite/blob/master/kona-demo/src/main/java/com/tencent/kona/demo/JettyServer.java#L99)加上语句
`sslContextFactory.setNeedClientAuth(true);`
然后客户端采用如下代码：
```
    @Test
    public void tlcpDemo() throws Exception {

        Security.addProvider(new KonaProvider());
        CloseableHttpClient client = createClient();

        HttpGet getMethod = new HttpGet(
                String.format("https://localhost:%d/jetty", 8443));
        CloseableHttpResponse response = client.execute(getMethod);
        client.close();
        HttpEntity entity = response.getEntity();
        if (entity != null) {
            String responseString = EntityUtils.toString(entity);
            System.out.println(responseString); // 输出服务器返回的字符串
        }
        response.close();
    }

    // Create Apache HttpClient client, which supports TLCP connection.
    private static CloseableHttpClient createClient() throws Exception {
        SSLContext context = createContext();

        SSLConnectionSocketFactory socketFactory
                = new SSLConnectionSocketFactory(context);
        CloseableHttpClient httpClient = HttpClients.custom()
                .setSSLSocketFactory(socketFactory).build();
        return httpClient;
    }

    private static SSLContext createContext() throws Exception {
        // Load trust store
        KeyStore trustStore = KeyStore.getInstance("PKCS12", "Kona");
        try (FileInputStream keyStoreIn = new FileInputStream(
                TRUSTSTORE.toFile())) {
            trustStore.load(keyStoreIn, TRUSTSTOREPASSWORD.toCharArray());
        }

        TrustManagerFactory tmf = TrustManagerFactory.getInstance("PKIX", "Kona");
        tmf.init(trustStore);

        // Load key store
        KeyStore keyStore = KeyStore.getInstance("PKCS12", "Kona");
        try (FileInputStream keyStoreIn = new FileInputStream(
                KEYSTORE.toFile())) {
            keyStore.load(keyStoreIn, KEYSTOREPASSWORD.toCharArray());
        }
        KeyManagerFactory kmf = KeyManagerFactory.getInstance("NewSunX509", "Kona");
        kmf.init(keyStore, KEYSTOREPASSWORD.toCharArray());

        SSLContext context = SSLContext.getInstance("TLCPv1.1", "Kona");
        context.init(kmf.getKeyManagers(), tmf.getTrustManagers(), new SecureRandom());
        return context;
    }
```
调用，结果报如下错误：
```
08:46:44.663 [main] DEBUG org.apache.http.impl.execchain.RetryExec - Software caused connection abort: socket write error
java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at com.tencent.kona.sun.security.ssl.SSLSocketOutputRecord.encodeChangeCipherSpec(SSLSocketOutputRecord.java:231)
	at com.tencent.kona.sun.security.ssl.OutputRecord.changeWriteCiphers(OutputRecord.java:188)
	at com.tencent.kona.sun.security.ssl.TLCPChangeCipherSpec$TLCPChangeCipherSpecProducer.produce(TLCPChangeCipherSpec.java:112)
	at com.tencent.kona.sun.security.ssl.TLCPFinished$TLCPFinishedProducer.onProduceFinished(TLCPFinished.java:397)
	at com.tencent.kona.sun.security.ssl.TLCPFinished$TLCPFinishedProducer.produce(TLCPFinished.java:381)
	at com.tencent.kona.sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:472)
	at com.tencent.kona.sun.security.ssl.ServerHelloDone$ServerHelloDoneConsumer.consume(ServerHelloDone.java:183)
	at com.tencent.kona.sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:428)
	at com.tencent.kona.sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:502)
	at com.tencent.kona.sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:473)
	at com.tencent.kona.sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
	at com.tencent.kona.sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1508)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1423)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at PersonalTest.tlcpDemo(PersonalTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
```

**Comment by johnshajiang** [comment]
```
java.io.IOException: Unknown named curve: 1.2.156.10197.1.301
	at sun.security.util.ECParameters.engineInit(ECParameters.java:141)
	at java.security.AlgorithmParameters.init(AlgorithmParameters.java:293)
	at sun.security.x509.AlgorithmId.decodeParams(AlgorithmId.java:151)
	at sun.security.x509.AlgorithmId.<init>(AlgorithmId.java:133)
	at sun.security.x509.AlgorithmId.parse(AlgorithmId.java:413)
	at sun.security.x509.X509Key.parse(X509Key.java:168)
	at sun.security.x509.CertificateX509Key.<init>(CertificateX509Key.java:75)
	at sun.security.x509.X509CertInfo.parse(X509CertInfo.java:667)
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:167)
	at sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1849)
	at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:189)
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:102)
```

从上面的异常可以看出，代码最终是调用的JDK中的X.509实现，而没有用上TencentKonaSMSuite中的实现。JDK肯定是不支持国密的。

#637 解决了这个问题。

**Comment by johnshajiang** [comment]
另外，[TLCPWithJettyDemo]是令Jetty server使用上了TencentKonaSMSuite的`SSLContext`实现，所以就没有遇到问题。这种方式也更为直接。

[TLCPWithJettyDemo]:
https://github.com/Tencent/TencentKonaSMSuite/blob/master/kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLCPWithJettyDemo.java#L275

**Comment by nhhc-lxr** [comment]
> ```
> java.io.IOException: Unknown named curve: 1.2.156.10197.1.301
> 	at sun.security.util.ECParameters.engineInit(ECParameters.java:141)
> 	at java.security.AlgorithmParameters.init(AlgorithmParameters.java:293)
> 	at sun.security.x509.AlgorithmId.decodeParams(AlgorithmId.java:151)
> 	at sun.security.x509.AlgorithmId.<init>(AlgorithmId.java:133)
> 	at sun.security.x509.AlgorithmId.parse(AlgorithmId.java:413)
> 	at sun.security.x509.X509Key.parse(X509Key.java:168)
> 	at sun.security.x509.CertificateX509Key.<init>(CertificateX509Key.java:75)
> 	at sun.security.x509.X509CertInfo.parse(X509CertInfo.java:667)
> 	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:167)
> 	at sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1849)
> 	at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:189)
> 	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:102)
> ```
> 
> 从上面的异常可以看出，代码最终是调用的JDK中的X.509实现，而没有用上TencentKonaSMSuite中的实现。JDK肯定是不支持国密的。
> 
> #637 解决了这个问题，令`JettyServer`支持了client auth。 但默认情况下，没有启用client auth。`application.yml`中有`client-auth-enabled: false`。

原来如此，sslContextFactory也需要用setProvider(”Kona“)才能生效，学到了学到了，非常感谢您的指点

**Comment by johnshajiang** [comment]
@nhhc-lxr 
如果该问题已得到解决，请关闭该issue。
若有其它问题，欢迎提交新的issue。
