### ISSUE TITLE
使用 KeyPairGenerator.getInstance("SM2", KonaProvider.NAME) 生成的公钥，无法被解析

### ISSUE THREAD

**Issue by eamonzzz** [Tencent/TencentKonaSMSuite#651]
不确定是否是测试方法不对还是其他原因，使用 “SM2” 算法时，生成的公钥无法被解析

测试方法如下：
```java
static final char[] PWD = "123456".toCharArray();
    @Test
    void testPkcs12() throws Exception {
        Security.addProvider(new KonaProvider());
        KeyPairGenerator keyPairGenerator
                = KeyPairGenerator.getInstance("SM2", KonaProvider.NAME);
        keyPairGenerator.initialize(SM2ParameterSpec.instance());
        KeyPair keyPair = keyPairGenerator.generateKeyPair();
        ECPublicKey pubKey = (ECPublicKey) keyPair.getPublic();
        ECPrivateKey priKey = (ECPrivateKey) keyPair.getPrivate();

        X509Certificate x509Certificate = generateTestCertificate(new X500Name("CN=Test"), pubKey, priKey);

        KeyStore pkcs12 = KeyStore.getInstance("PKCS12",KonaProvider.NAME);
        pkcs12.load(null, null);
        pkcs12.setKeyEntry("sign", priKey, PWD, new Certificate[]{x509Certificate});


    }

    /**
     * 创建自签名证书
     */
    X509Certificate generateTestCertificate(X500Name subjectDn, PublicKey publicKey, PrivateKey privateKey) throws CertificateException, OperatorCreationException {

        JcaX509v3CertificateBuilder certificateBuilder = new JcaX509v3CertificateBuilder(subjectDn, BigInteger.TEN, new Date(), new Date(), subjectDn, publicKey);
        ContentSigner contentSigner = new JcaContentSignerBuilder("SM3withSM2").build(privateKey);
        X509CertificateHolder x509CertificateHolder = certificateBuilder.build(contentSigner);

        JcaX509CertificateConverter certificateConverter = new JcaX509CertificateConverter().setProvider(BouncyCastleProvider.PROVIDER_NAME);
        return certificateConverter.getCertificate(x509CertificateHolder);

    }
```

在执行 new JcaX509v3CertificateBuilder 方法时，抛出异常：
```java
java.lang.IllegalArgumentException: failed to construct sequence from byte[]: Extra data detected in stream
	at org.bouncycastle.asn1.ASN1Sequence.getInstance(ASN1Sequence.java:101)
	at org.bouncycastle.asn1.x509.SubjectPublicKeyInfo.getInstance(SubjectPublicKeyInfo.java:44)
	at org.bouncycastle.cert.jcajce.JcaX509v3CertificateBuilder.<init>(Unknown Source)
	at test.gmca.KonaTlcpServerTest.generateTestCertificate(KonaTlcpServerTest.java:98)
	at test.gmca.KonaTlcpServerTest.testPkcs12(KonaTlcpServerTest.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:119)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:94)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:89)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)


```

**Comment by johnshajiang** [comment]
由`KeyPairGenerator.getInstance("SM2")`生成的密钥对中的私角与公钥都是无格式的。
请试试`KeyPairGenerator.getInstance("EC")`，然后指定使用椭圆曲线`curveSM2`。它生成的私钥格式为PKCS#8，而公钥格式为X.509。可以参考这个[测试]。

[测试]:
https://github.com/Tencent/TencentKonaSMSuite/blob/master/kona-crypto/src/test/java/com/tencent/kona/crypto/provider/ECKeyPairGeneratorTest.java#L71

**Comment by eamonzzz** [comment]
> 由`KeyPairGenerator.getInstance("SM2")`生成的密钥对中的私角与公钥都是无格式的。 请试试`KeyPairGenerator.getInstance("EC")`，然后指定使用椭圆曲线`curveSM2`。它生成的私钥格式为PKCS#8，而公钥格式为X.509。可以参考这个[测试](https://github.com/Tencent/TencentKonaSMSuite/blob/master/kona-crypto/src/test/java/com/tencent/kona/crypto/provider/ECKeyPairGeneratorTest.java#L71)。

OK，请问一下，SM2PrivateKey 主要作用是什么？我怎样才能将 SM2PrivateKey 转换成 PKCS#8 格式呢？

**Comment by johnshajiang** [comment]
> SM2PrivateKey 主要作用是什么？

`KeyPairGenerator.getInstance("SM2")`，即`SM2KeyPairGenerator`，以及`SM2PrivateKey`和`SM2PublicKey`，是为了应对一些不需要格式化的场景。
SM2PrivateKey就是包装了一个256位的大整数作为私钥；SM2PublicKey则是包装了一个公钥点的两个坐标值，每个坐标值均为256位的大整数。

所谓的格式，如PKCS#8，只不过是加入了一些额外的信息。比如这个密钥是用的什么算法，如果是EC算法，那么它用的是什么椭圆曲线等等。
有些场景已经明确只使用SM2算法，那些信息就都是确定的，并不需要包装到格式中。

> 我怎样才能将 SM2PrivateKey 转换成 PKCS#8 格式呢？

如果使用Kona国密套件，那么`KeyPairGenerator.getInstance("EC")`，即`ECKeyPairGenerator`，生成的私钥就是PKCS#8格式的。
如果使用其它的组件生成的是无格式的密钥，那么可以使用`KeyFactory.getInstance("EC", "Kona")`，将私钥转化为PKCS#8格式（使用`PKCS8EncodedKeySpec`）。

**Comment by nikbobo** [comment]
能否支持 SM2 公私钥 EC 格式和 SM2 格式的相互转换？

**Comment by johnshajiang** [comment]
@nikbobo 
> 能否支持 SM2 公私钥 EC 格式和 SM2 格式的相互转换？

本项目可以自动地支持这两类格式，并不需要特别转换。
其实`SM2PublicKey`也是`ECPublicKey`；`SM2PrivateKey`也是`ECPrivateKey`。

**Comment by nikbobo** [comment]
我想需要一种可以转换 SM2 公私钥格式的工具。
比如说，前端可能对于 SM2 公私钥是原始格式，Hex 编码。
在 Java 这边，可能是 X509 和 PKCS8，在 OpenSSL 这边可能是 RFC5915 这样，Base64 编码。
编码的问题我们可以自己处理，但是现在遇到的问题是 OpenSSL 直接产生的 SM2 公私钥是另一种格式，没法进行转换。

**Comment by johnshajiang** [comment]
> 但是现在遇到的问题是 OpenSSL 直接产生的 SM2 公私钥是另一种格式，没法进行转换。

能否先给一组命令，以展示你是如何使用OpenSSL生成SM2密钥对？

**Comment by johnshajiang** [comment]
@nikbobo 
> 但是现在遇到的问题是 OpenSSL 直接产生的 SM2 公私钥是另一种格式，没法进行转换。

能否先给一组命令，以展示你是如何使用OpenSSL生成SM2密钥对？

**Comment by johnshajiang** [comment]
@nikbobo 
另外，我建议你为这个问题新开一个issue。
