### ISSUE TITLE
ssldemo error withio.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record

### ISSUE THREAD

**Issue by MingLouis** [Tencent/TencentKonaSMSuite#838]

**Comment by MingLouis** [comment]
按照demo编写，会报错io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 160101004501000041010193ffb64700a66c63dada406a62f0a4a30d4a0ba46544cb6f4885146e32b65bd9000002e013010000160010000e000c02683208485454502f312e3100230000
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 160101004501000041010193ffb64700a66c63dada406a62f0a4a30d4a0ba46544cb6f4885146e32b65bd9000002e013010000160010000e000c02683208485454502f312e3100230000
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1246)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	... 17 more

看到之前有个类似的问题是切换了高版本netty就解决了，但是我目前的版本是4.1.86.Final，还是报上面的错，可以麻烦看下吗

**Comment by MingLouis** [comment]
测试项目地址 https://github.com/MingLouis/comm-tlcp.git

**Comment by meteor199** [comment]
kona升级到最新版本试下呢

**Comment by johnshajiang** [comment]
@MingLouis 
能否试试#770 提及的测试工程：
https://github.com/meteor199/issue-kona-ssl/
该工程使用Netty版本为4.1.109.Final。

**Comment by MingLouis** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.1.RELEASE</version>
        <relativePath/>
    </parent>

    <groupId>com.nrxt</groupId>
    <artifactId>comm-tlcp</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
        </dependency>



        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjweaver</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.109.Final</version>
        </dependency>

        
        <dependency>
            <groupId>com.tencent.kona</groupId>
            <artifactId>kona-provider</artifactId>
            <version>1.0.13</version>
        </dependency>
        
        <dependency>
            <groupId>com.tencent.kona</groupId>
            <artifactId>kona-crypto</artifactId>
            <version>1.0.13</version>
        </dependency>
        
        <dependency>
            <groupId>com.tencent.kona</groupId>
            <artifactId>kona-pkix</artifactId>
            <version>1.0.13</version>
        </dependency>
        
        <dependency>
            <groupId>com.tencent.kona</groupId>
            <artifactId>kona-ssl</artifactId>
            <version>1.0.13</version>
        </dependency>


    </dependencies>
</project>`


已经切换了版本 还是会报这个错误

**Comment by johnshajiang** [comment]
@MingLouis 
如果使用TLS 1.3，你的工程是可以正常工作的。
但使用TLCP，该工程的服务端则会报`not an SSL/TLS record`。感觉是Netty服务端无法识别TLCP协议。
但是使用WireShark分析流量时，它是可以识别出该工程Netty客户端发送的TLCP协议的ClientHello消息。

**Comment by MingLouis** [comment]
> @MingLouis 如果使用TLS 1.3，你的工程是可以正常工作的。 但使用TLCP，该工程的服务端则会报`not an SSL/TLS record`。感觉是Netty服务端无法识别TLCP协议。 但是使用WireShark分析流量时，它是可以识别出该工程Netty客户端发送的TLCP协议的ClientHello消息。

请问这个问题如何才能解决，我的核心代码都来源于项目给出的demo，kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLCPWithNettyDemo.java

**Comment by MingLouis** [comment]
进一步排查发现是com.tencent.kona.sun.security.ssl.SSLEngineImpl#beginHandshake 这个方法报的错，netty在握手阶段的时候 ，服务端的io.netty.handler.ssl.SslUtils#getEncryptedPacketLength(io.netty.buffer.ByteBuf, int) 方法会报NOT_ENCRYPTED未加密异常 @johnshajiang 可以帮忙看一下么

**Comment by MingLouis** [comment]
https://github.com/Tencent/TencentKonaSMSuite/blob/a7aa6489e04658cc7bba5e89b623d37c0a3aa689/kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLCPWithNettyDemo.java
此demo的298行
`pipeline.addLast(sslContext.newHandler(ch.alloc()));`  会调用netty提供的SSLUtil类，这个类无法识别TLCP的版本号，所以报这个错误，请问netty还有其他什么方式可以调用成功？ @johnshajiang

**Comment by johnshajiang** [comment]
看起来SslUtils.java可以识别GMSSL/TLCP协议，它设定了这个协议的版本号，即`0x0101`。
https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslUtils.java#L67

Netty在2021年就支持了GMSSL/TLCP协议，
https://github.com/netty/netty/commit/3226e774853f95b50f0d2955e41884efebc9225f

**Comment by MingLouis** [comment]
> 看起来SslUtils.java可以识别GMSSL/TLCP协议，它设定了这个协议的版本号，即`0x0101`。 https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslUtils.java#L67
> 
> Netty在2021年就支持了GMSSL/TLCP协议， [netty/netty@3226e77](https://github.com/netty/netty/commit/3226e774853f95b50f0d2955e41884efebc9225f)

谢谢，经过再次排查 是因为我的springboot版本是2.3.1.RELEASE，导致netty的版本只能依赖到4.1.50.Final，此版本不支持GMSSL，所以导致上面的报错。目前springboot升级到2.7.18，netty的依赖可以提升到4.1.101.Final，已解决此问题。
![微信截图_20240828201046](https://github.com/user-attachments/assets/2adb632a-5fbd-4f3f-9be1-992693abb9e0)
