### ISSUE TITLE
连接tongsuo总是提示证书找不到问题

### ISSUE THREAD

**Issue by ckz119** [Tencent/TencentKonaSMSuite#873]
你好！为啥我连接tongsuo总提示证书找不到，异常信息如下：
Exception in thread "main" javax.net.ssl.SSLHandshakeException: (certificate_unknown) PKIX path building failed: com.tencent.kona.sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.tencent.kona.sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at com.tencent.kona.sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
	at com.tencent.kona.sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
	at com.tencent.kona.sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
	at com.tencent.kona.sun.security.ssl.TLCPCertificate$TLCPCertificateConsumer.checkServerCerts(TLCPCertificate.java:752)
	at com.tencent.kona.sun.security.ssl.TLCPCertificate$TLCPCertificateConsumer.onCertificate(TLCPCertificate.java:500)
	at com.tencent.kona.sun.security.ssl.TLCPCertificate$TLCPCertificateConsumer.consume(TLCPCertificate.java:389)
	at com.tencent.kona.sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:424)
	at com.tencent.kona.sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:502)
	at com.tencent.kona.sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:473)
	at com.tencent.kona.sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
	at com.tencent.kona.sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1508)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1423)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
	at ckz.config.SSLTest.main(SSLTest.java:27)
Caused by: com.tencent.kona.sun.security.validator.ValidatorException: PKIX path building failed: com.tencent.kona.sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.tencent.kona.sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:391)
	at com.tencent.kona.sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:245)
	at com.tencent.kona.sun.security.validator.Validator.validate(Validator.java:256)
	at com.tencent.kona.sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:232)
	at com.tencent.kona.sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:133)
	at com.tencent.kona.sun.security.ssl.TLCPCertificate$TLCPCertificateConsumer.checkServerCerts(TLCPCertificate.java:736)
	... 15 more
Caused by: com.tencent.kona.sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.tencent.kona.sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
	at com.tencent.kona.sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at com.tencent.kona.sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:386)
	... 20 more

证书我都是用的铜锁官方版本库测试的证书。

下面是我的代码：
public static SSLSocketFactory getSocketFactory(final String caCrtFile,
                                                    final String crtFile,
                                                    final String keyFile,
                                                    final String password) {

        try(FileInputStream fis = new FileInputStream(ResourceUtils.getFile(caCrtFile));
            BufferedInputStream bis = new BufferedInputStream(fis);
            BufferedInputStream c = new BufferedInputStream(new FileInputStream(ResourceUtils.getFile(crtFile)));
            PEMParser pemParser = new PEMParser(new FileReader(ResourceUtils.getFile(keyFile)))) {
            Security.addProvider(new BouncyCastleProvider());

            // 加载 CA 证书
            X509Certificate caCert = null;

            CertificateFactory cf = CertificateFactory.getInstance("X.509","KonaPKIX");

            while (bis.available() > 0) {
                caCert = (X509Certificate) cf.generateCertificate(bis);
            }

            // 加载客户端证书

            X509Certificate cert = null;
            while (c.available() > 0) {
                cert = (X509Certificate) cf.generateCertificate(c);
            }

            // 加载客户端私钥

            Object object = pemParser.readObject();
            JcaPEMKeyConverter converter = new JcaPEMKeyConverter().setProvider("BC");
            //KeyPair key = converter.getKeyPair((PEMKeyPair) object);
             PrivateKey privateKey=converter.getPrivateKey((PrivateKeyInfo) object);

            // CA 证书用于验证服务器身份
            KeyStore caKs = KeyStore.getInstance("PKCS12","KonaPKIX");
            caKs.load(null, password.toCharArray());
            caKs.setCertificateEntry("ca-certificate", caCert);
            TrustManagerFactory tmf = TrustManagerFactory.getInstance("PKIX","KonaSSL");
            tmf.init(caKs);

            // 客户端密钥和证书将发送到 Server，以便它可以进行身份验证
            KeyStore ks = KeyStore.getInstance("PKCS12","KonaPKIX");
            ks.load(null, null);
            ks.setCertificateEntry("certificate", cert);
            ks.setKeyEntry("private-key", privateKey, password.toCharArray(),
                    new java.security.cert.Certificate[]{cert});
            KeyManagerFactory kmf = KeyManagerFactory.getInstance("NewSunX509");
            kmf.init(ks, password.toCharArray());

            // finally, create SSL socket factory
            SSLContext context = SSLContext.getInstance("TLCPv1.1","KonaSSL");
            context.init(null, null, new SecureRandom());
            return context.getSocketFactory();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

**Comment by johnshajiang** [comment]
```
Caused by: java.security.cert.CertificateException: No subject alternative names present
    at com.tencent.kona.sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:137)
    at com.tencent.kona.sun.security.util.HostnameChecker.match(HostnameChecker.java:100)
    ...
```
请参考：
https://stackoverflow.com/questions/29157861/java-certificateexception-no-subject-alternative-names-matching-ip-address

**Comment by ckz119** [comment]
> ```
> Caused by: java.security.cert.CertificateException: No subject alternative names present
>     at com.tencent.kona.sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:137)
>     at com.tencent.kona.sun.security.util.HostnameChecker.match(HostnameChecker.java:100)
>     ...
> ```
> 
> 请参考： https://stackoverflow.com/questions/29157861/java-certificateexception-no-subject-alternative-names-matching-ip-address

好的。非常感谢！

**Comment by johnshajiang** [comment]
@ckz119 
不客气。
欢迎为本项目加星 ;-)
