### ISSUE TITLE
oracle jdk 1.8 201 RSA证书报错 getParams找不到

### ISSUE THREAD

**Issue by meteor199** [Tencent/TencentKonaSMSuite#902]
在oracle中，使用tls 1.2访问自签名证书的网站报错：

```
JDK Version: 1.8.0_201
Java Home: C:\Program Files\Java\oracle_jdk1.8.0_201\jre
Java Vendor: Oracle Corporation
VM Version: 25.201-b09
VM Name: Java HotSpot(TM) 64-Bit Server VM
Exception in thread "main" java.lang.NoSuchMethodError: java.security.interfaces.RSAKey.getParams()Ljava/security/spec/AlgorithmParameterSpec;
	at com.tencent.kona.sun.security.rsa.RSAPSSSignature.isValid(RSAPSSSignature.java:262)
	at com.tencent.kona.sun.security.rsa.RSAPSSSignature.isPublicKeyValid(RSAPSSSignature.java:253)
	at com.tencent.kona.sun.security.rsa.RSAPSSSignature.engineInitVerify(RSAPSSSignature.java:128)
	at java.security.Signature$Delegate.engineInitVerify(Signature.java:1168)
	at java.security.Signature.initVerify(Signature.java:460)
	at com.tencent.kona.jdk.internal.misc.SharedSecretsUtil.secSignatureInitVerify(SharedSecretsUtil.java:302)
	at com.tencent.kona.sun.security.util.SignatureUtil.initVerifyWithParam(SignatureUtil.java:174)
	at com.tencent.kona.sun.security.ssl.SignatureScheme.getVerifier(SignatureScheme.java:617)
	at com.tencent.kona.sun.security.ssl.CertificateVerify$T13CertificateVerifyMessage.<init>(CertificateVerify.java:1015)
	at com.tencent.kona.sun.security.ssl.CertificateVerify$T13CertificateVerifyConsumer.consume(CertificateVerify.java:1171)
	at com.tencent.kona.sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:424)
	at com.tencent.kona.sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:502)
	at com.tencent.kona.sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:473)
	at com.tencent.kona.sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
	at com.tencent.kona.sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1508)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1423)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.example.RsaHttpDemo.requestWithKona(RsaHttpDemo.java:94)
	at org.example.RsaHttpDemo.main(RsaHttpDemo.java:24)
	at org.example.Main.main(Main.java:34)
```

在 401版本是正常的
```
JDK Version: 1.8.0_401
Java Home: C:\Program Files\Java\jdk-1.8\jre
Java Vendor: Oracle Corporation
VM Version: 25.401-b10
VM Name: Java HotSpot(TM) 64-Bit Server VM
Hello world!11
Response Code: 200

```

**Comment by meteor199** [comment]
代码

```
    private static void requestWithKona(){
        try {
//
//            System.setProperty("http.proxyHost", "me.me");
//            System.setProperty("http.proxyPort", "20171");
//            System.setProperty("https.proxyHost", "me.me");
//            System.setProperty("https.proxyPort", "20171");
            // 创建URL对象
//            URL url = new URL("https://untrusted-root.badssl.com/");
            URL url = new URL("https://test.com:8443");

            // 打开连接
            HttpsURLConnection connection = (HttpsURLConnection) url.openConnection();

            SSLContext serverSSLContext = SSLContext.getInstance("TLCP", "Kona");
            TrustManagerFactory tmf = TrustManagerFactory.getInstance("PKIX", "Kona");
//            KeyStore trustStore = createTrustStore(readFileToString("certs/BadSSL Untrusted Root Certificate Authority.crt"));

            KeyStore trustStore = createTrustStore(readFileToString("../certs/test/root.crt"));
            tmf.init(trustStore);
            serverSSLContext.init(null,tmf.getTrustManagers(), null);

            connection.setSSLSocketFactory(serverSSLContext.getSocketFactory());
            // 设置请求方法
            connection.setRequestMethod("GET");

            // 获取响应代码
            int responseCode = connection.getResponseCode();
            System.out.println("Response Code: " + responseCode);

            // 读取响应内容
            BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            String inputLine;
            StringBuilder content = new StringBuilder();
            while ((inputLine = in.readLine()) != null) {
                content.append(inputLine);
            }

            // 关闭输入流
            in.close();

            // 断开连接
            connection.disconnect();

            // 打印响应内容
            System.out.println("Response Content: " + content.toString());

        } catch (Exception e) {
            e.printStackTrace();
        }
    }



    private static KeyStore createTrustStore(String caStr)
            throws Exception {
        KeyStore trustStore = KeyStore.getInstance("JKS", "Kona");
        trustStore.load(null, null);
        trustStore.setCertificateEntry("demo", loadCert(caStr));
        return trustStore;
    }


    public static String readFileToString(String filePath) throws IOException {
        // 使用 Files.readAllBytes 读取文件内容
        byte[] fileBytes = Files.readAllBytes(Paths.get(filePath));
        // 将字节数组转换为字符串
        return new String(fileBytes);
    }
    private static X509Certificate loadCert(String certPEM)
            throws Exception {
        CertificateFactory certFactory = CertificateFactory.getInstance(
                "X.509");
        X509Certificate x509Cert = (X509Certificate) certFactory.generateCertificate(
                new ByteArrayInputStream(certPEM.getBytes()));

        return x509Cert;
    }



```

**Comment by meteor199** [comment]
[ssl_certs.zip](https://github.com/user-attachments/files/17410117/ssl_certs.zip)
这是证书信息。访问 https://untrusted-root.badssl.com 是正常的，但是访问自己搭建的网站就报错了。

nginx配置
```

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
       listen       8443 ssl;
       server_name  test.com;

       ssl_certificate      chain.crt;
       ssl_certificate_key  private.key;

       ssl_session_cache    shared:SSL:1m;
       ssl_session_timeout  5m;

       ssl_ciphers  HIGH:!aNULL:!MD5;
       ssl_prefer_server_ciphers  on;

       location / {
           root   html;
           index  index.html index.htm;
       }
    }

}

```

**Comment by johnshajiang** [comment]
> Exception in thread "main" java.lang.NoSuchMethodError: java.security.interfaces.RSAKey.getParams()Ljava/security/spec/AlgorithmParameterSpec;

这说明低版本没有这个API。
对于RSA算法，应该还是使用JDK中的实现。

**Comment by meteor199** [comment]
好的
