### ISSUE TITLE
作为TLCP客户端，单向认证问题

### ISSUE THREAD

**Issue by tt-libr** [Tencent/TencentKonaSMSuite#944]
```
private static SSLContext createContext(String caCert, KeyStore keyStore, String password) throws Exception {
    // 生成信任的CA机构证书KeyStore
    KeyStore trustStore = createTrustStore(caCert);

    // 生成rustManager
    TrustManagerFactory tmf = TrustManagerFactory.getInstance("PKIX", "KonaSSL");
    tmf.init(trustStore);
    TrustManager[] tm = tmf.getTrustManagers();

    // 生成KeyManager
    KeyManagerFactory kmf = KeyManagerFactory.getInstance("NewSunX509", "KonaSSL");
    kmf.init(keyStore, password.toCharArray());
    KeyManager[] km = kmf.getKeyManagers();

    // 构建SSLContext
    SSLContext sslContext = SSLContext.getInstance("TLCPv1.1", "KonaSSL");
    sslContext.init(km, tm, new SecureRandom());
    return sslContext;
 }
```

作为TLCP客户端封装的这个方法，目前实现了和服务端tengine双向认证通信，现准备改造为单向认证（希望达到无需配置使用客户端加密证书和签名证书），可以怎么改造下支持单向认证呢？可以创建一个默认的KeyManager吗？
```[tasklist]
### Tasks
```

**Comment by johnshajiang** [comment]
客户端可以不需要`KeyManager`，即`km`为`null`。

**Comment by tt-libr** [comment]
> 客户端可以不需要`KeyManager`，即`km`为`null`。

我这边将KeyManager设置为null和空数组均报错，这是设置为null调用后的报错信息，麻烦作者及大家帮忙看下什么原因。看起来是
`KeyExchange`这一步发生错误了，难道和服务端tengine有关?
```
javax.net.ssl.SSLException: (internal_error) null
	at com.tencent.kona.sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at com.tencent.kona.sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
	at com.tencent.kona.sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
	at com.tencent.kona.sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1708)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:471)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at cn.anxin.sm.tlcpsupport.http.ApacheHttpClient.doGet(ApacheHttpClient.java:77)
	at cn.anxin.sm.tlcpsupport.TLCPTest.testGet(TLCPTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.NullPointerException
	at com.tencent.kona.sun.security.ssl.SM2EKeyExchange$SM2EPossession.<init>(SM2EKeyExchange.java:129)
	at com.tencent.kona.sun.security.ssl.SM2EClientKeyExchange$SM2EClientKeyExchangeProducer.produce(SM2EClientKeyExchange.java:170)
	at com.tencent.kona.sun.security.ssl.ClientKeyExchange$ClientKeyExchangeProducer.produce(ClientKeyExchange.java:66)
	at com.tencent.kona.sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:468)
	at com.tencent.kona.sun.security.ssl.ServerHelloDone$ServerHelloDoneConsumer.consume(ServerHelloDone.java:183)
	at com.tencent.kona.sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:424)
	at com.tencent.kona.sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:502)
	at com.tencent.kona.sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:473)
	at com.tencent.kona.sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
	at com.tencent.kona.sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1508)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1423)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
```

这是服务端tengine配置：
```
server {
    listen 32000 ssl;
server_tokens off;
    server_name  10.64.2.101;
    enable_ntls on;
    ssl_ciphers ECDHE-SM2-SM4-CBC-SM3:ECDHE-SM2-SM4-GCM-SM3:ECC-SM2-SM4-CBC-SM3:ECC-SM2-SM4-GCM-SM3;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    default_type            text/plain;
    add_header  "Content-Type" "text/html;charset=utf-8";
    ssl_verify_client off;
    ssl_sign_certificate /data/cert/tyyy-test/yygl.sm2.sign.cer.pem;
    ssl_sign_certificate_key /data/cert/tyyy-test/yygl.sm2.sign.prikey.p8.pem;
    ssl_enc_certificate /data/cert/tyyy-test/yygl.sm2.encrypt.cer.pem;
    ssl_enc_certificate_key /data/cert/tyyy-test/yygl.sm2.encrypt.prikey.p8.pem;

    error_page  404              /404.html;
             
    error_page   500 502 503 504  /500.html;
    location = /500.html {
            root   error;
                   }

    location = /404.html {
            root   error;
    }
}
```
这是客户端代码：
```
private static SSLContext createContext(String caCert, KeyStore keyStore, String password) throws Exception {

    // 生成信任的CA机构证书KeyStore
    KeyStore trustStore = createTrustStore(caCert);

    // 生成rustManager
    TrustManagerFactory tmf = TrustManagerFactory.getInstance("PKIX", "KonaSSL");
    tmf.init(trustStore);
    TrustManager[] tm = tmf.getTrustManagers();

    // 构建SSLContext
    SSLContext sslContext = SSLContext.getInstance("TLCPv1.1", "KonaSSL");
    sslContext.init(null, tm, new SecureRandom());
    return sslContext;
}
```

**Comment by johnshajiang** [comment]
```
Caused by: java.lang.NullPointerException
	at com.tencent.kona.sun.security.ssl.SM2EKeyExchange$SM2EPossession.<init>(SM2EKeyExchange.java:129)
	at com.tencent.kona.sun.security.ssl.SM2EClientKeyExchange$SM2EClientKeyExchangeProducer.produce(SM2EClientKeyExchange.java:170)
	at com.tencent.kona.sun.security.ssl.ClientKeyExchange$ClientKeyExchangeProducer.produce(ClientKeyExchange.java:66)
```
你是用的什么加密套件？`ECDHE-SM4-CBC-SM3`或`ECDHE-SM4-GCM-SM3`？
`ECDHE-*`类的加密套件要求客户端也要有双证书，但`ECC-*`类加密套件，如`ECC-SM4-CBC-SM3`，则没有这个要求。。

**Comment by tt-libr** [comment]
> ```
> Caused by: java.lang.NullPointerException
> 	at com.tencent.kona.sun.security.ssl.SM2EKeyExchange$SM2EPossession.<init>(SM2EKeyExchange.java:129)
> 	at com.tencent.kona.sun.security.ssl.SM2EClientKeyExchange$SM2EClientKeyExchangeProducer.produce(SM2EClientKeyExchange.java:170)
> 	at com.tencent.kona.sun.security.ssl.ClientKeyExchange$ClientKeyExchangeProducer.produce(ClientKeyExchange.java:66)
> ```
> 
> 你是用的什么加密套件？`ECDHE-SM4-CBC-SM3`或`ECDHE-SM4-GCM-SM3`？ `ECDHE-*`类的加密套件要求客户端也要有双证书，但`ECC-*`类加密套件，如`ECC-SM4-CBC-SM3`，则没有这个要求。
> 
> > ssl_ciphers ECDHE-SM2-SM4-CBC-SM3:ECDHE-SM2-SM4-GCM-SM3:ECC-SM2-SM4-CBC-SM3:ECC-SM2-SM4-GCM-SM3;
> 
> 服务端偏好`ECDHE-*`类加密套件，那么客户端可能优先选择了`ECDHE-SM2-SM4-CBC-SM3`。

确实是算法套件的问题，我在客户端配置了`ECC-*`类加密套件后，已经解决这个问题，谢谢作者~
![1732764993326](https://github.com/user-attachments/assets/ec4b57c5-1f74-4552-a138-3eb70ff034ea)

**Comment by tt-libr** [comment]
我关闭了哈
